spring:
  application:
    name: ActivityService
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://esmm.systeo.tn/realms/systeodigital/protocol/openid-connect/certs
          issuer-uri: https://esmm.systeo.tn/realms/systeodigital
          audiences: app-projectPFE
          enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  rabbitmq:
    host: 161.97.88.195
    port: 5672
    username: admin
    password: admin
    template:
      retry:
        enabled: true
        initial-interval: 2000
        max-interval: 5000
        max-attempts: 3

eureka:
  instance:
    hostname: e4.systeo.tn
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: https://eureka.systeo.tn/eureka/

server:
  port: 8075

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG

keycloak:
  client-id: app-projectPFE
  client-secret: 5FfaiB11tLGbFcuwcgUZYgj0OaeYIaUX

storage:
  location: ./activity-storage

rabbitmq:
  exchange:
    name: exchange.ProjectService.TaskCreated
  queueJson:
    name: queue.ActivityService.taskCreated
  routing:
    json:
      key:
        name: ProjectService.envoye.ActivityService